{{ if .Values.enableWebhook }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "spark-operator.fullname" . }}-webhook
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.webhookPort }}
    name: webhook
  selector:
    {{- include "spark-operator.selectorLabels" . | nindent 4 }}
{{ end }}
