/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// DependenciesApplyConfiguration represents a declarative configuration of the Dependencies type for use
// with apply.
type DependenciesApplyConfiguration struct {
	Jars            []string `json:"jars,omitempty"`
	Files           []string `json:"files,omitempty"`
	PyFiles         []string `json:"pyFiles,omitempty"`
	Packages        []string `json:"packages,omitempty"`
	ExcludePackages []string `json:"excludePackages,omitempty"`
	Repositories    []string `json:"repositories,omitempty"`
	Archives        []string `json:"archives,omitempty"`
}

// DependenciesApplyConfiguration constructs a declarative configuration of the Dependencies type for use with
// apply.
func Dependencies() *DependenciesApplyConfiguration {
	return &DependenciesApplyConfiguration{}
}

// WithJars adds the given value to the Jars field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Jars field.
func (b *DependenciesApplyConfiguration) WithJars(values ...string) *DependenciesApplyConfiguration {
	for i := range values {
		b.Jars = append(b.Jars, values[i])
	}
	return b
}

// WithFiles adds the given value to the Files field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Files field.
func (b *DependenciesApplyConfiguration) WithFiles(values ...string) *DependenciesApplyConfiguration {
	for i := range values {
		b.Files = append(b.Files, values[i])
	}
	return b
}

// WithPyFiles adds the given value to the PyFiles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PyFiles field.
func (b *DependenciesApplyConfiguration) WithPyFiles(values ...string) *DependenciesApplyConfiguration {
	for i := range values {
		b.PyFiles = append(b.PyFiles, values[i])
	}
	return b
}

// WithPackages adds the given value to the Packages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Packages field.
func (b *DependenciesApplyConfiguration) WithPackages(values ...string) *DependenciesApplyConfiguration {
	for i := range values {
		b.Packages = append(b.Packages, values[i])
	}
	return b
}

// WithExcludePackages adds the given value to the ExcludePackages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludePackages field.
func (b *DependenciesApplyConfiguration) WithExcludePackages(values ...string) *DependenciesApplyConfiguration {
	for i := range values {
		b.ExcludePackages = append(b.ExcludePackages, values[i])
	}
	return b
}

// WithRepositories adds the given value to the Repositories field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Repositories field.
func (b *DependenciesApplyConfiguration) WithRepositories(values ...string) *DependenciesApplyConfiguration {
	for i := range values {
		b.Repositories = append(b.Repositories, values[i])
	}
	return b
}

// WithArchives adds the given value to the Archives field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Archives field.
func (b *DependenciesApplyConfiguration) WithArchives(values ...string) *DependenciesApplyConfiguration {
	for i := range values {
		b.Archives = append(b.Archives, values[i])
	}
	return b
}
