/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
)

// DriverIngressConfigurationApplyConfiguration represents a declarative configuration of the DriverIngressConfiguration type for use
// with apply.
type DriverIngressConfigurationApplyConfiguration struct {
	ServicePort        *int32                    `json:"servicePort,omitempty"`
	ServicePortName    *string                   `json:"servicePortName,omitempty"`
	ServiceType        *v1.ServiceType           `json:"serviceType,omitempty"`
	ServiceAnnotations map[string]string         `json:"serviceAnnotations,omitempty"`
	ServiceLabels      map[string]string         `json:"serviceLabels,omitempty"`
	IngressURLFormat   *string                   `json:"ingressURLFormat,omitempty"`
	IngressAnnotations map[string]string         `json:"ingressAnnotations,omitempty"`
	IngressTLS         []networkingv1.IngressTLS `json:"ingressTLS,omitempty"`
}

// DriverIngressConfigurationApplyConfiguration constructs a declarative configuration of the DriverIngressConfiguration type for use with
// apply.
func DriverIngressConfiguration() *DriverIngressConfigurationApplyConfiguration {
	return &DriverIngressConfigurationApplyConfiguration{}
}

// WithServicePort sets the ServicePort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePort field is set to the value of the last call.
func (b *DriverIngressConfigurationApplyConfiguration) WithServicePort(value int32) *DriverIngressConfigurationApplyConfiguration {
	b.ServicePort = &value
	return b
}

// WithServicePortName sets the ServicePortName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePortName field is set to the value of the last call.
func (b *DriverIngressConfigurationApplyConfiguration) WithServicePortName(value string) *DriverIngressConfigurationApplyConfiguration {
	b.ServicePortName = &value
	return b
}

// WithServiceType sets the ServiceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceType field is set to the value of the last call.
func (b *DriverIngressConfigurationApplyConfiguration) WithServiceType(value v1.ServiceType) *DriverIngressConfigurationApplyConfiguration {
	b.ServiceType = &value
	return b
}

// WithServiceAnnotations puts the entries into the ServiceAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ServiceAnnotations field,
// overwriting an existing map entries in ServiceAnnotations field with the same key.
func (b *DriverIngressConfigurationApplyConfiguration) WithServiceAnnotations(entries map[string]string) *DriverIngressConfigurationApplyConfiguration {
	if b.ServiceAnnotations == nil && len(entries) > 0 {
		b.ServiceAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ServiceAnnotations[k] = v
	}
	return b
}

// WithServiceLabels puts the entries into the ServiceLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ServiceLabels field,
// overwriting an existing map entries in ServiceLabels field with the same key.
func (b *DriverIngressConfigurationApplyConfiguration) WithServiceLabels(entries map[string]string) *DriverIngressConfigurationApplyConfiguration {
	if b.ServiceLabels == nil && len(entries) > 0 {
		b.ServiceLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ServiceLabels[k] = v
	}
	return b
}

// WithIngressURLFormat sets the IngressURLFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressURLFormat field is set to the value of the last call.
func (b *DriverIngressConfigurationApplyConfiguration) WithIngressURLFormat(value string) *DriverIngressConfigurationApplyConfiguration {
	b.IngressURLFormat = &value
	return b
}

// WithIngressAnnotations puts the entries into the IngressAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the IngressAnnotations field,
// overwriting an existing map entries in IngressAnnotations field with the same key.
func (b *DriverIngressConfigurationApplyConfiguration) WithIngressAnnotations(entries map[string]string) *DriverIngressConfigurationApplyConfiguration {
	if b.IngressAnnotations == nil && len(entries) > 0 {
		b.IngressAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.IngressAnnotations[k] = v
	}
	return b
}

// WithIngressTLS adds the given value to the IngressTLS field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IngressTLS field.
func (b *DriverIngressConfigurationApplyConfiguration) WithIngressTLS(values ...networkingv1.IngressTLS) *DriverIngressConfigurationApplyConfiguration {
	for i := range values {
		b.IngressTLS = append(b.IngressTLS, values[i])
	}
	return b
}
