/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// DriverInfoApplyConfiguration represents a declarative configuration of the DriverInfo type for use
// with apply.
type DriverInfoApplyConfiguration struct {
	WebUIServiceName    *string `json:"webUIServiceName,omitempty"`
	WebUIAddress        *string `json:"webUIAddress,omitempty"`
	WebUIPort           *int32  `json:"webUIPort,omitempty"`
	WebUIIngressName    *string `json:"webUIIngressName,omitempty"`
	WebUIIngressAddress *string `json:"webUIIngressAddress,omitempty"`
	PodName             *string `json:"podName,omitempty"`
}

// DriverInfoApplyConfiguration constructs a declarative configuration of the DriverInfo type for use with
// apply.
func DriverInfo() *DriverInfoApplyConfiguration {
	return &DriverInfoApplyConfiguration{}
}

// WithWebUIServiceName sets the WebUIServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebUIServiceName field is set to the value of the last call.
func (b *DriverInfoApplyConfiguration) WithWebUIServiceName(value string) *DriverInfoApplyConfiguration {
	b.WebUIServiceName = &value
	return b
}

// WithWebUIAddress sets the WebUIAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebUIAddress field is set to the value of the last call.
func (b *DriverInfoApplyConfiguration) WithWebUIAddress(value string) *DriverInfoApplyConfiguration {
	b.WebUIAddress = &value
	return b
}

// WithWebUIPort sets the WebUIPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebUIPort field is set to the value of the last call.
func (b *DriverInfoApplyConfiguration) WithWebUIPort(value int32) *DriverInfoApplyConfiguration {
	b.WebUIPort = &value
	return b
}

// WithWebUIIngressName sets the WebUIIngressName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebUIIngressName field is set to the value of the last call.
func (b *DriverInfoApplyConfiguration) WithWebUIIngressName(value string) *DriverInfoApplyConfiguration {
	b.WebUIIngressName = &value
	return b
}

// WithWebUIIngressAddress sets the WebUIIngressAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebUIIngressAddress field is set to the value of the last call.
func (b *DriverInfoApplyConfiguration) WithWebUIIngressAddress(value string) *DriverInfoApplyConfiguration {
	b.WebUIIngressAddress = &value
	return b
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *DriverInfoApplyConfiguration) WithPodName(value string) *DriverInfoApplyConfiguration {
	b.PodName = &value
	return b
}
