/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// DynamicAllocationApplyConfiguration represents a declarative configuration of the DynamicAllocation type for use
// with apply.
type DynamicAllocationApplyConfiguration struct {
	Enabled                *bool  `json:"enabled,omitempty"`
	InitialExecutors       *int32 `json:"initialExecutors,omitempty"`
	MinExecutors           *int32 `json:"minExecutors,omitempty"`
	MaxExecutors           *int32 `json:"maxExecutors,omitempty"`
	ShuffleTrackingTimeout *int64 `json:"shuffleTrackingTimeout,omitempty"`
}

// DynamicAllocationApplyConfiguration constructs a declarative configuration of the DynamicAllocation type for use with
// apply.
func DynamicAllocation() *DynamicAllocationApplyConfiguration {
	return &DynamicAllocationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *DynamicAllocationApplyConfiguration) WithEnabled(value bool) *DynamicAllocationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithInitialExecutors sets the InitialExecutors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialExecutors field is set to the value of the last call.
func (b *DynamicAllocationApplyConfiguration) WithInitialExecutors(value int32) *DynamicAllocationApplyConfiguration {
	b.InitialExecutors = &value
	return b
}

// WithMinExecutors sets the MinExecutors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinExecutors field is set to the value of the last call.
func (b *DynamicAllocationApplyConfiguration) WithMinExecutors(value int32) *DynamicAllocationApplyConfiguration {
	b.MinExecutors = &value
	return b
}

// WithMaxExecutors sets the MaxExecutors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxExecutors field is set to the value of the last call.
func (b *DynamicAllocationApplyConfiguration) WithMaxExecutors(value int32) *DynamicAllocationApplyConfiguration {
	b.MaxExecutors = &value
	return b
}

// WithShuffleTrackingTimeout sets the ShuffleTrackingTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShuffleTrackingTimeout field is set to the value of the last call.
func (b *DynamicAllocationApplyConfiguration) WithShuffleTrackingTimeout(value int64) *DynamicAllocationApplyConfiguration {
	b.ShuffleTrackingTimeout = &value
	return b
}
