/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// GPUSpecApplyConfiguration represents a declarative configuration of the GPUSpec type for use
// with apply.
type GPUSpecApplyConfiguration struct {
	Name     *string `json:"name,omitempty"`
	Quantity *int64  `json:"quantity,omitempty"`
}

// GPUSpecApplyConfiguration constructs a declarative configuration of the GPUSpec type for use with
// apply.
func GPUSpec() *GPUSpecApplyConfiguration {
	return &GPUSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GPUSpecApplyConfiguration) WithName(value string) *GPUSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithQuantity sets the Quantity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quantity field is set to the value of the last call.
func (b *GPUSpecApplyConfiguration) WithQuantity(value int64) *GPUSpecApplyConfiguration {
	b.Quantity = &value
	return b
}
