/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// MonitoringSpecApplyConfiguration represents a declarative configuration of the MonitoringSpec type for use
// with apply.
type MonitoringSpecApplyConfiguration struct {
	ExposeDriverMetrics   *bool                             `json:"exposeDriverMetrics,omitempty"`
	ExposeExecutorMetrics *bool                             `json:"exposeExecutorMetrics,omitempty"`
	MetricsProperties     *string                           `json:"metricsProperties,omitempty"`
	MetricsPropertiesFile *string                           `json:"metricsPropertiesFile,omitempty"`
	Prometheus            *PrometheusSpecApplyConfiguration `json:"prometheus,omitempty"`
}

// MonitoringSpecApplyConfiguration constructs a declarative configuration of the MonitoringSpec type for use with
// apply.
func MonitoringSpec() *MonitoringSpecApplyConfiguration {
	return &MonitoringSpecApplyConfiguration{}
}

// WithExposeDriverMetrics sets the ExposeDriverMetrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExposeDriverMetrics field is set to the value of the last call.
func (b *MonitoringSpecApplyConfiguration) WithExposeDriverMetrics(value bool) *MonitoringSpecApplyConfiguration {
	b.ExposeDriverMetrics = &value
	return b
}

// WithExposeExecutorMetrics sets the ExposeExecutorMetrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExposeExecutorMetrics field is set to the value of the last call.
func (b *MonitoringSpecApplyConfiguration) WithExposeExecutorMetrics(value bool) *MonitoringSpecApplyConfiguration {
	b.ExposeExecutorMetrics = &value
	return b
}

// WithMetricsProperties sets the MetricsProperties field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsProperties field is set to the value of the last call.
func (b *MonitoringSpecApplyConfiguration) WithMetricsProperties(value string) *MonitoringSpecApplyConfiguration {
	b.MetricsProperties = &value
	return b
}

// WithMetricsPropertiesFile sets the MetricsPropertiesFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsPropertiesFile field is set to the value of the last call.
func (b *MonitoringSpecApplyConfiguration) WithMetricsPropertiesFile(value string) *MonitoringSpecApplyConfiguration {
	b.MetricsPropertiesFile = &value
	return b
}

// WithPrometheus sets the Prometheus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prometheus field is set to the value of the last call.
func (b *MonitoringSpecApplyConfiguration) WithPrometheus(value *PrometheusSpecApplyConfiguration) *MonitoringSpecApplyConfiguration {
	b.Prometheus = value
	return b
}
