/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// NamePathApplyConfiguration represents a declarative configuration of the NamePath type for use
// with apply.
type NamePathApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

// NamePathApplyConfiguration constructs a declarative configuration of the NamePath type for use with
// apply.
func NamePath() *NamePathApplyConfiguration {
	return &NamePathApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamePathApplyConfiguration) WithName(value string) *NamePathApplyConfiguration {
	b.Name = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *NamePathApplyConfiguration) WithPath(value string) *NamePathApplyConfiguration {
	b.Path = &value
	return b
}
