/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// PrometheusSpecApplyConfiguration represents a declarative configuration of the PrometheusSpec type for use
// with apply.
type PrometheusSpecApplyConfiguration struct {
	JmxExporterJar *string `json:"jmxExporterJar,omitempty"`
	Port           *int32  `json:"port,omitempty"`
	PortName       *string `json:"portName,omitempty"`
	ConfigFile     *string `json:"configFile,omitempty"`
	Configuration  *string `json:"configuration,omitempty"`
}

// PrometheusSpecApplyConfiguration constructs a declarative configuration of the PrometheusSpec type for use with
// apply.
func PrometheusSpec() *PrometheusSpecApplyConfiguration {
	return &PrometheusSpecApplyConfiguration{}
}

// WithJmxExporterJar sets the JmxExporterJar field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JmxExporterJar field is set to the value of the last call.
func (b *PrometheusSpecApplyConfiguration) WithJmxExporterJar(value string) *PrometheusSpecApplyConfiguration {
	b.JmxExporterJar = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *PrometheusSpecApplyConfiguration) WithPort(value int32) *PrometheusSpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithPortName sets the PortName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortName field is set to the value of the last call.
func (b *PrometheusSpecApplyConfiguration) WithPortName(value string) *PrometheusSpecApplyConfiguration {
	b.PortName = &value
	return b
}

// WithConfigFile sets the ConfigFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigFile field is set to the value of the last call.
func (b *PrometheusSpecApplyConfiguration) WithConfigFile(value string) *PrometheusSpecApplyConfiguration {
	b.ConfigFile = &value
	return b
}

// WithConfiguration sets the Configuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Configuration field is set to the value of the last call.
func (b *PrometheusSpecApplyConfiguration) WithConfiguration(value string) *PrometheusSpecApplyConfiguration {
	b.Configuration = &value
	return b
}
