/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kubeflow/spark-operator/api/v1beta2"
)

// RestartPolicyApplyConfiguration represents a declarative configuration of the RestartPolicy type for use
// with apply.
type RestartPolicyApplyConfiguration struct {
	Type                             *apiv1beta2.RestartPolicyType `json:"type,omitempty"`
	OnSubmissionFailureRetries       *int32                        `json:"onSubmissionFailureRetries,omitempty"`
	OnFailureRetries                 *int32                        `json:"onFailureRetries,omitempty"`
	OnSubmissionFailureRetryInterval *int64                        `json:"onSubmissionFailureRetryInterval,omitempty"`
	OnFailureRetryInterval           *int64                        `json:"onFailureRetryInterval,omitempty"`
}

// RestartPolicyApplyConfiguration constructs a declarative configuration of the RestartPolicy type for use with
// apply.
func RestartPolicy() *RestartPolicyApplyConfiguration {
	return &RestartPolicyApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RestartPolicyApplyConfiguration) WithType(value apiv1beta2.RestartPolicyType) *RestartPolicyApplyConfiguration {
	b.Type = &value
	return b
}

// WithOnSubmissionFailureRetries sets the OnSubmissionFailureRetries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnSubmissionFailureRetries field is set to the value of the last call.
func (b *RestartPolicyApplyConfiguration) WithOnSubmissionFailureRetries(value int32) *RestartPolicyApplyConfiguration {
	b.OnSubmissionFailureRetries = &value
	return b
}

// WithOnFailureRetries sets the OnFailureRetries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnFailureRetries field is set to the value of the last call.
func (b *RestartPolicyApplyConfiguration) WithOnFailureRetries(value int32) *RestartPolicyApplyConfiguration {
	b.OnFailureRetries = &value
	return b
}

// WithOnSubmissionFailureRetryInterval sets the OnSubmissionFailureRetryInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnSubmissionFailureRetryInterval field is set to the value of the last call.
func (b *RestartPolicyApplyConfiguration) WithOnSubmissionFailureRetryInterval(value int64) *RestartPolicyApplyConfiguration {
	b.OnSubmissionFailureRetryInterval = &value
	return b
}

// WithOnFailureRetryInterval sets the OnFailureRetryInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnFailureRetryInterval field is set to the value of the last call.
func (b *RestartPolicyApplyConfiguration) WithOnFailureRetryInterval(value int64) *RestartPolicyApplyConfiguration {
	b.OnFailureRetryInterval = &value
	return b
}
