/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kubeflow/spark-operator/api/v1beta2"
)

// ScheduledSparkApplicationSpecApplyConfiguration represents a declarative configuration of the ScheduledSparkApplicationSpec type for use
// with apply.
type ScheduledSparkApplicationSpecApplyConfiguration struct {
	Schedule                  *string                                 `json:"schedule,omitempty"`
	TimeZone                  *string                                 `json:"timeZone,omitempty"`
	Template                  *SparkApplicationSpecApplyConfiguration `json:"template,omitempty"`
	Suspend                   *bool                                   `json:"suspend,omitempty"`
	ConcurrencyPolicy         *apiv1beta2.ConcurrencyPolicy           `json:"concurrencyPolicy,omitempty"`
	SuccessfulRunHistoryLimit *int32                                  `json:"successfulRunHistoryLimit,omitempty"`
	FailedRunHistoryLimit     *int32                                  `json:"failedRunHistoryLimit,omitempty"`
}

// ScheduledSparkApplicationSpecApplyConfiguration constructs a declarative configuration of the ScheduledSparkApplicationSpec type for use with
// apply.
func ScheduledSparkApplicationSpec() *ScheduledSparkApplicationSpecApplyConfiguration {
	return &ScheduledSparkApplicationSpecApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *ScheduledSparkApplicationSpecApplyConfiguration) WithSchedule(value string) *ScheduledSparkApplicationSpecApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithTimeZone sets the TimeZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeZone field is set to the value of the last call.
func (b *ScheduledSparkApplicationSpecApplyConfiguration) WithTimeZone(value string) *ScheduledSparkApplicationSpecApplyConfiguration {
	b.TimeZone = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ScheduledSparkApplicationSpecApplyConfiguration) WithTemplate(value *SparkApplicationSpecApplyConfiguration) *ScheduledSparkApplicationSpecApplyConfiguration {
	b.Template = value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ScheduledSparkApplicationSpecApplyConfiguration) WithSuspend(value bool) *ScheduledSparkApplicationSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithConcurrencyPolicy sets the ConcurrencyPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConcurrencyPolicy field is set to the value of the last call.
func (b *ScheduledSparkApplicationSpecApplyConfiguration) WithConcurrencyPolicy(value apiv1beta2.ConcurrencyPolicy) *ScheduledSparkApplicationSpecApplyConfiguration {
	b.ConcurrencyPolicy = &value
	return b
}

// WithSuccessfulRunHistoryLimit sets the SuccessfulRunHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessfulRunHistoryLimit field is set to the value of the last call.
func (b *ScheduledSparkApplicationSpecApplyConfiguration) WithSuccessfulRunHistoryLimit(value int32) *ScheduledSparkApplicationSpecApplyConfiguration {
	b.SuccessfulRunHistoryLimit = &value
	return b
}

// WithFailedRunHistoryLimit sets the FailedRunHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedRunHistoryLimit field is set to the value of the last call.
func (b *ScheduledSparkApplicationSpecApplyConfiguration) WithFailedRunHistoryLimit(value int32) *ScheduledSparkApplicationSpecApplyConfiguration {
	b.FailedRunHistoryLimit = &value
	return b
}
