/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kubeflow/spark-operator/api/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ScheduledSparkApplicationStatusApplyConfiguration represents a declarative configuration of the ScheduledSparkApplicationStatus type for use
// with apply.
type ScheduledSparkApplicationStatusApplyConfiguration struct {
	LastRun                *v1.Time                  `json:"lastRun,omitempty"`
	NextRun                *v1.Time                  `json:"nextRun,omitempty"`
	LastRunName            *string                   `json:"lastRunName,omitempty"`
	PastSuccessfulRunNames []string                  `json:"pastSuccessfulRunNames,omitempty"`
	PastFailedRunNames     []string                  `json:"pastFailedRunNames,omitempty"`
	ScheduleState          *apiv1beta2.ScheduleState `json:"scheduleState,omitempty"`
	Reason                 *string                   `json:"reason,omitempty"`
}

// ScheduledSparkApplicationStatusApplyConfiguration constructs a declarative configuration of the ScheduledSparkApplicationStatus type for use with
// apply.
func ScheduledSparkApplicationStatus() *ScheduledSparkApplicationStatusApplyConfiguration {
	return &ScheduledSparkApplicationStatusApplyConfiguration{}
}

// WithLastRun sets the LastRun field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRun field is set to the value of the last call.
func (b *ScheduledSparkApplicationStatusApplyConfiguration) WithLastRun(value v1.Time) *ScheduledSparkApplicationStatusApplyConfiguration {
	b.LastRun = &value
	return b
}

// WithNextRun sets the NextRun field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextRun field is set to the value of the last call.
func (b *ScheduledSparkApplicationStatusApplyConfiguration) WithNextRun(value v1.Time) *ScheduledSparkApplicationStatusApplyConfiguration {
	b.NextRun = &value
	return b
}

// WithLastRunName sets the LastRunName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRunName field is set to the value of the last call.
func (b *ScheduledSparkApplicationStatusApplyConfiguration) WithLastRunName(value string) *ScheduledSparkApplicationStatusApplyConfiguration {
	b.LastRunName = &value
	return b
}

// WithPastSuccessfulRunNames adds the given value to the PastSuccessfulRunNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PastSuccessfulRunNames field.
func (b *ScheduledSparkApplicationStatusApplyConfiguration) WithPastSuccessfulRunNames(values ...string) *ScheduledSparkApplicationStatusApplyConfiguration {
	for i := range values {
		b.PastSuccessfulRunNames = append(b.PastSuccessfulRunNames, values[i])
	}
	return b
}

// WithPastFailedRunNames adds the given value to the PastFailedRunNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PastFailedRunNames field.
func (b *ScheduledSparkApplicationStatusApplyConfiguration) WithPastFailedRunNames(values ...string) *ScheduledSparkApplicationStatusApplyConfiguration {
	for i := range values {
		b.PastFailedRunNames = append(b.PastFailedRunNames, values[i])
	}
	return b
}

// WithScheduleState sets the ScheduleState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScheduleState field is set to the value of the last call.
func (b *ScheduledSparkApplicationStatusApplyConfiguration) WithScheduleState(value apiv1beta2.ScheduleState) *ScheduledSparkApplicationStatusApplyConfiguration {
	b.ScheduleState = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *ScheduledSparkApplicationStatusApplyConfiguration) WithReason(value string) *ScheduledSparkApplicationStatusApplyConfiguration {
	b.Reason = &value
	return b
}
