/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/api/core/v1"
)

// SparkPodSpecApplyConfiguration represents a declarative configuration of the SparkPodSpec type for use
// with apply.
type SparkPodSpecApplyConfiguration struct {
	Template                      *v1.PodTemplateSpec                  `json:"template,omitempty"`
	Cores                         *int32                               `json:"cores,omitempty"`
	CoreLimit                     *string                              `json:"coreLimit,omitempty"`
	Memory                        *string                              `json:"memory,omitempty"`
	MemoryLimit                   *string                              `json:"memoryLimit,omitempty"`
	MemoryOverhead                *string                              `json:"memoryOverhead,omitempty"`
	GPU                           *GPUSpecApplyConfiguration           `json:"gpu,omitempty"`
	Image                         *string                              `json:"image,omitempty"`
	ConfigMaps                    []NamePathApplyConfiguration         `json:"configMaps,omitempty"`
	Secrets                       []SecretInfoApplyConfiguration       `json:"secrets,omitempty"`
	Env                           []v1.EnvVar                          `json:"env,omitempty"`
	EnvVars                       map[string]string                    `json:"envVars,omitempty"`
	EnvFrom                       []v1.EnvFromSource                   `json:"envFrom,omitempty"`
	EnvSecretKeyRefs              map[string]NameKeyApplyConfiguration `json:"envSecretKeyRefs,omitempty"`
	Labels                        map[string]string                    `json:"labels,omitempty"`
	Annotations                   map[string]string                    `json:"annotations,omitempty"`
	VolumeMounts                  []v1.VolumeMount                     `json:"volumeMounts,omitempty"`
	Affinity                      *v1.Affinity                         `json:"affinity,omitempty"`
	Tolerations                   []v1.Toleration                      `json:"tolerations,omitempty"`
	PodSecurityContext            *v1.PodSecurityContext               `json:"podSecurityContext,omitempty"`
	SecurityContext               *v1.SecurityContext                  `json:"securityContext,omitempty"`
	SchedulerName                 *string                              `json:"schedulerName,omitempty"`
	Sidecars                      []v1.Container                       `json:"sidecars,omitempty"`
	InitContainers                []v1.Container                       `json:"initContainers,omitempty"`
	HostNetwork                   *bool                                `json:"hostNetwork,omitempty"`
	NodeSelector                  map[string]string                    `json:"nodeSelector,omitempty"`
	DNSConfig                     *v1.PodDNSConfig                     `json:"dnsConfig,omitempty"`
	TerminationGracePeriodSeconds *int64                               `json:"terminationGracePeriodSeconds,omitempty"`
	ServiceAccount                *string                              `json:"serviceAccount,omitempty"`
	HostAliases                   []v1.HostAlias                       `json:"hostAliases,omitempty"`
	ShareProcessNamespace         *bool                                `json:"shareProcessNamespace,omitempty"`
}

// SparkPodSpecApplyConfiguration constructs a declarative configuration of the SparkPodSpec type for use with
// apply.
func SparkPodSpec() *SparkPodSpecApplyConfiguration {
	return &SparkPodSpecApplyConfiguration{}
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithTemplate(value v1.PodTemplateSpec) *SparkPodSpecApplyConfiguration {
	b.Template = &value
	return b
}

// WithCores sets the Cores field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cores field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithCores(value int32) *SparkPodSpecApplyConfiguration {
	b.Cores = &value
	return b
}

// WithCoreLimit sets the CoreLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CoreLimit field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithCoreLimit(value string) *SparkPodSpecApplyConfiguration {
	b.CoreLimit = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithMemory(value string) *SparkPodSpecApplyConfiguration {
	b.Memory = &value
	return b
}

// WithMemoryLimit sets the MemoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryLimit field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithMemoryLimit(value string) *SparkPodSpecApplyConfiguration {
	b.MemoryLimit = &value
	return b
}

// WithMemoryOverhead sets the MemoryOverhead field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryOverhead field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithMemoryOverhead(value string) *SparkPodSpecApplyConfiguration {
	b.MemoryOverhead = &value
	return b
}

// WithGPU sets the GPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GPU field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithGPU(value *GPUSpecApplyConfiguration) *SparkPodSpecApplyConfiguration {
	b.GPU = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithImage(value string) *SparkPodSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithConfigMaps adds the given value to the ConfigMaps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ConfigMaps field.
func (b *SparkPodSpecApplyConfiguration) WithConfigMaps(values ...*NamePathApplyConfiguration) *SparkPodSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConfigMaps")
		}
		b.ConfigMaps = append(b.ConfigMaps, *values[i])
	}
	return b
}

// WithSecrets adds the given value to the Secrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Secrets field.
func (b *SparkPodSpecApplyConfiguration) WithSecrets(values ...*SecretInfoApplyConfiguration) *SparkPodSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSecrets")
		}
		b.Secrets = append(b.Secrets, *values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *SparkPodSpecApplyConfiguration) WithEnv(values ...v1.EnvVar) *SparkPodSpecApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithEnvVars puts the entries into the EnvVars field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EnvVars field,
// overwriting an existing map entries in EnvVars field with the same key.
func (b *SparkPodSpecApplyConfiguration) WithEnvVars(entries map[string]string) *SparkPodSpecApplyConfiguration {
	if b.EnvVars == nil && len(entries) > 0 {
		b.EnvVars = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EnvVars[k] = v
	}
	return b
}

// WithEnvFrom adds the given value to the EnvFrom field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EnvFrom field.
func (b *SparkPodSpecApplyConfiguration) WithEnvFrom(values ...v1.EnvFromSource) *SparkPodSpecApplyConfiguration {
	for i := range values {
		b.EnvFrom = append(b.EnvFrom, values[i])
	}
	return b
}

// WithEnvSecretKeyRefs puts the entries into the EnvSecretKeyRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EnvSecretKeyRefs field,
// overwriting an existing map entries in EnvSecretKeyRefs field with the same key.
func (b *SparkPodSpecApplyConfiguration) WithEnvSecretKeyRefs(entries map[string]NameKeyApplyConfiguration) *SparkPodSpecApplyConfiguration {
	if b.EnvSecretKeyRefs == nil && len(entries) > 0 {
		b.EnvSecretKeyRefs = make(map[string]NameKeyApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.EnvSecretKeyRefs[k] = v
	}
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *SparkPodSpecApplyConfiguration) WithLabels(entries map[string]string) *SparkPodSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *SparkPodSpecApplyConfiguration) WithAnnotations(entries map[string]string) *SparkPodSpecApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithVolumeMounts adds the given value to the VolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeMounts field.
func (b *SparkPodSpecApplyConfiguration) WithVolumeMounts(values ...v1.VolumeMount) *SparkPodSpecApplyConfiguration {
	for i := range values {
		b.VolumeMounts = append(b.VolumeMounts, values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithAffinity(value v1.Affinity) *SparkPodSpecApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *SparkPodSpecApplyConfiguration) WithTolerations(values ...v1.Toleration) *SparkPodSpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithPodSecurityContext sets the PodSecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSecurityContext field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithPodSecurityContext(value v1.PodSecurityContext) *SparkPodSpecApplyConfiguration {
	b.PodSecurityContext = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithSecurityContext(value v1.SecurityContext) *SparkPodSpecApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithSchedulerName sets the SchedulerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulerName field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithSchedulerName(value string) *SparkPodSpecApplyConfiguration {
	b.SchedulerName = &value
	return b
}

// WithSidecars adds the given value to the Sidecars field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sidecars field.
func (b *SparkPodSpecApplyConfiguration) WithSidecars(values ...v1.Container) *SparkPodSpecApplyConfiguration {
	for i := range values {
		b.Sidecars = append(b.Sidecars, values[i])
	}
	return b
}

// WithInitContainers adds the given value to the InitContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InitContainers field.
func (b *SparkPodSpecApplyConfiguration) WithInitContainers(values ...v1.Container) *SparkPodSpecApplyConfiguration {
	for i := range values {
		b.InitContainers = append(b.InitContainers, values[i])
	}
	return b
}

// WithHostNetwork sets the HostNetwork field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostNetwork field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithHostNetwork(value bool) *SparkPodSpecApplyConfiguration {
	b.HostNetwork = &value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *SparkPodSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *SparkPodSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithDNSConfig sets the DNSConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSConfig field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithDNSConfig(value v1.PodDNSConfig) *SparkPodSpecApplyConfiguration {
	b.DNSConfig = &value
	return b
}

// WithTerminationGracePeriodSeconds sets the TerminationGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminationGracePeriodSeconds field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithTerminationGracePeriodSeconds(value int64) *SparkPodSpecApplyConfiguration {
	b.TerminationGracePeriodSeconds = &value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithServiceAccount(value string) *SparkPodSpecApplyConfiguration {
	b.ServiceAccount = &value
	return b
}

// WithHostAliases adds the given value to the HostAliases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HostAliases field.
func (b *SparkPodSpecApplyConfiguration) WithHostAliases(values ...v1.HostAlias) *SparkPodSpecApplyConfiguration {
	for i := range values {
		b.HostAliases = append(b.HostAliases, values[i])
	}
	return b
}

// WithShareProcessNamespace sets the ShareProcessNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShareProcessNamespace field is set to the value of the last call.
func (b *SparkPodSpecApplyConfiguration) WithShareProcessNamespace(value bool) *SparkPodSpecApplyConfiguration {
	b.ShareProcessNamespace = &value
	return b
}
