/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kubeflow/spark-operator/api/v1beta2"
	v1 "k8s.io/api/core/v1"
)

// SparkApplicationSpecApplyConfiguration represents a declarative configuration of the SparkApplicationSpec type for use
// with apply.
type SparkApplicationSpecApplyConfiguration struct {
	Type                  *apiv1beta2.SparkApplicationType               `json:"type,omitempty"`
	SparkVersion          *string                                        `json:"sparkVersion,omitempty"`
	Mode                  *apiv1beta2.DeployMode                         `json:"mode,omitempty"`
	ProxyUser             *string                                        `json:"proxyUser,omitempty"`
	Image                 *string                                        `json:"image,omitempty"`
	ImagePullPolicy       *string                                        `json:"imagePullPolicy,omitempty"`
	ImagePullSecrets      []string                                       `json:"imagePullSecrets,omitempty"`
	MainClass             *string                                        `json:"mainClass,omitempty"`
	MainApplicationFile   *string                                        `json:"mainApplicationFile,omitempty"`
	Arguments             []string                                       `json:"arguments,omitempty"`
	SparkConf             map[string]string                              `json:"sparkConf,omitempty"`
	HadoopConf            map[string]string                              `json:"hadoopConf,omitempty"`
	SparkConfigMap        *string                                        `json:"sparkConfigMap,omitempty"`
	HadoopConfigMap       *string                                        `json:"hadoopConfigMap,omitempty"`
	Volumes               []v1.Volume                                    `json:"volumes,omitempty"`
	Driver                *DriverSpecApplyConfiguration                  `json:"driver,omitempty"`
	Executor              *ExecutorSpecApplyConfiguration                `json:"executor,omitempty"`
	Deps                  *DependenciesApplyConfiguration                `json:"deps,omitempty"`
	RestartPolicy         *RestartPolicyApplyConfiguration               `json:"restartPolicy,omitempty"`
	NodeSelector          map[string]string                              `json:"nodeSelector,omitempty"`
	FailureRetries        *int32                                         `json:"failureRetries,omitempty"`
	RetryInterval         *int64                                         `json:"retryInterval,omitempty"`
	PythonVersion         *string                                        `json:"pythonVersion,omitempty"`
	MemoryOverheadFactor  *string                                        `json:"memoryOverheadFactor,omitempty"`
	Monitoring            *MonitoringSpecApplyConfiguration              `json:"monitoring,omitempty"`
	BatchScheduler        *string                                        `json:"batchScheduler,omitempty"`
	TimeToLiveSeconds     *int64                                         `json:"timeToLiveSeconds,omitempty"`
	BatchSchedulerOptions *BatchSchedulerConfigurationApplyConfiguration `json:"batchSchedulerOptions,omitempty"`
	SparkUIOptions        *SparkUIConfigurationApplyConfiguration        `json:"sparkUIOptions,omitempty"`
	DriverIngressOptions  []DriverIngressConfigurationApplyConfiguration `json:"driverIngressOptions,omitempty"`
	DynamicAllocation     *DynamicAllocationApplyConfiguration           `json:"dynamicAllocation,omitempty"`
}

// SparkApplicationSpecApplyConfiguration constructs a declarative configuration of the SparkApplicationSpec type for use with
// apply.
func SparkApplicationSpec() *SparkApplicationSpecApplyConfiguration {
	return &SparkApplicationSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithType(value apiv1beta2.SparkApplicationType) *SparkApplicationSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithSparkVersion sets the SparkVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SparkVersion field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithSparkVersion(value string) *SparkApplicationSpecApplyConfiguration {
	b.SparkVersion = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithMode(value apiv1beta2.DeployMode) *SparkApplicationSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithProxyUser sets the ProxyUser field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyUser field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithProxyUser(value string) *SparkApplicationSpecApplyConfiguration {
	b.ProxyUser = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithImage(value string) *SparkApplicationSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithImagePullPolicy(value string) *SparkApplicationSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *SparkApplicationSpecApplyConfiguration) WithImagePullSecrets(values ...string) *SparkApplicationSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithMainClass sets the MainClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainClass field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithMainClass(value string) *SparkApplicationSpecApplyConfiguration {
	b.MainClass = &value
	return b
}

// WithMainApplicationFile sets the MainApplicationFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainApplicationFile field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithMainApplicationFile(value string) *SparkApplicationSpecApplyConfiguration {
	b.MainApplicationFile = &value
	return b
}

// WithArguments adds the given value to the Arguments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Arguments field.
func (b *SparkApplicationSpecApplyConfiguration) WithArguments(values ...string) *SparkApplicationSpecApplyConfiguration {
	for i := range values {
		b.Arguments = append(b.Arguments, values[i])
	}
	return b
}

// WithSparkConf puts the entries into the SparkConf field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SparkConf field,
// overwriting an existing map entries in SparkConf field with the same key.
func (b *SparkApplicationSpecApplyConfiguration) WithSparkConf(entries map[string]string) *SparkApplicationSpecApplyConfiguration {
	if b.SparkConf == nil && len(entries) > 0 {
		b.SparkConf = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SparkConf[k] = v
	}
	return b
}

// WithHadoopConf puts the entries into the HadoopConf field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the HadoopConf field,
// overwriting an existing map entries in HadoopConf field with the same key.
func (b *SparkApplicationSpecApplyConfiguration) WithHadoopConf(entries map[string]string) *SparkApplicationSpecApplyConfiguration {
	if b.HadoopConf == nil && len(entries) > 0 {
		b.HadoopConf = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.HadoopConf[k] = v
	}
	return b
}

// WithSparkConfigMap sets the SparkConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SparkConfigMap field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithSparkConfigMap(value string) *SparkApplicationSpecApplyConfiguration {
	b.SparkConfigMap = &value
	return b
}

// WithHadoopConfigMap sets the HadoopConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HadoopConfigMap field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithHadoopConfigMap(value string) *SparkApplicationSpecApplyConfiguration {
	b.HadoopConfigMap = &value
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *SparkApplicationSpecApplyConfiguration) WithVolumes(values ...v1.Volume) *SparkApplicationSpecApplyConfiguration {
	for i := range values {
		b.Volumes = append(b.Volumes, values[i])
	}
	return b
}

// WithDriver sets the Driver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Driver field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithDriver(value *DriverSpecApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.Driver = value
	return b
}

// WithExecutor sets the Executor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Executor field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithExecutor(value *ExecutorSpecApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.Executor = value
	return b
}

// WithDeps sets the Deps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deps field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithDeps(value *DependenciesApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.Deps = value
	return b
}

// WithRestartPolicy sets the RestartPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartPolicy field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithRestartPolicy(value *RestartPolicyApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.RestartPolicy = value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *SparkApplicationSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *SparkApplicationSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithFailureRetries sets the FailureRetries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureRetries field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithFailureRetries(value int32) *SparkApplicationSpecApplyConfiguration {
	b.FailureRetries = &value
	return b
}

// WithRetryInterval sets the RetryInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryInterval field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithRetryInterval(value int64) *SparkApplicationSpecApplyConfiguration {
	b.RetryInterval = &value
	return b
}

// WithPythonVersion sets the PythonVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PythonVersion field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithPythonVersion(value string) *SparkApplicationSpecApplyConfiguration {
	b.PythonVersion = &value
	return b
}

// WithMemoryOverheadFactor sets the MemoryOverheadFactor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryOverheadFactor field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithMemoryOverheadFactor(value string) *SparkApplicationSpecApplyConfiguration {
	b.MemoryOverheadFactor = &value
	return b
}

// WithMonitoring sets the Monitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitoring field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithMonitoring(value *MonitoringSpecApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.Monitoring = value
	return b
}

// WithBatchScheduler sets the BatchScheduler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BatchScheduler field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithBatchScheduler(value string) *SparkApplicationSpecApplyConfiguration {
	b.BatchScheduler = &value
	return b
}

// WithTimeToLiveSeconds sets the TimeToLiveSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeToLiveSeconds field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithTimeToLiveSeconds(value int64) *SparkApplicationSpecApplyConfiguration {
	b.TimeToLiveSeconds = &value
	return b
}

// WithBatchSchedulerOptions sets the BatchSchedulerOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BatchSchedulerOptions field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithBatchSchedulerOptions(value *BatchSchedulerConfigurationApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.BatchSchedulerOptions = value
	return b
}

// WithSparkUIOptions sets the SparkUIOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SparkUIOptions field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithSparkUIOptions(value *SparkUIConfigurationApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.SparkUIOptions = value
	return b
}

// WithDriverIngressOptions adds the given value to the DriverIngressOptions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DriverIngressOptions field.
func (b *SparkApplicationSpecApplyConfiguration) WithDriverIngressOptions(values ...*DriverIngressConfigurationApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDriverIngressOptions")
		}
		b.DriverIngressOptions = append(b.DriverIngressOptions, *values[i])
	}
	return b
}

// WithDynamicAllocation sets the DynamicAllocation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DynamicAllocation field is set to the value of the last call.
func (b *SparkApplicationSpecApplyConfiguration) WithDynamicAllocation(value *DynamicAllocationApplyConfiguration) *SparkApplicationSpecApplyConfiguration {
	b.DynamicAllocation = value
	return b
}
