/*
Copyright 2024 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	apiv1beta2 "github.com/kubeflow/spark-operator/api/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SparkApplicationStatusApplyConfiguration represents a declarative configuration of the SparkApplicationStatus type for use
// with apply.
type SparkApplicationStatusApplyConfiguration struct {
	SparkApplicationID        *string                             `json:"sparkApplicationId,omitempty"`
	SubmissionID              *string                             `json:"submissionID,omitempty"`
	LastSubmissionAttemptTime *v1.Time                            `json:"lastSubmissionAttemptTime,omitempty"`
	TerminationTime           *v1.Time                            `json:"terminationTime,omitempty"`
	DriverInfo                *DriverInfoApplyConfiguration       `json:"driverInfo,omitempty"`
	AppState                  *ApplicationStateApplyConfiguration `json:"applicationState,omitempty"`
	ExecutorState             map[string]apiv1beta2.ExecutorState `json:"executorState,omitempty"`
	ExecutionAttempts         *int32                              `json:"executionAttempts,omitempty"`
	SubmissionAttempts        *int32                              `json:"submissionAttempts,omitempty"`
}

// SparkApplicationStatusApplyConfiguration constructs a declarative configuration of the SparkApplicationStatus type for use with
// apply.
func SparkApplicationStatus() *SparkApplicationStatusApplyConfiguration {
	return &SparkApplicationStatusApplyConfiguration{}
}

// WithSparkApplicationID sets the SparkApplicationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SparkApplicationID field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithSparkApplicationID(value string) *SparkApplicationStatusApplyConfiguration {
	b.SparkApplicationID = &value
	return b
}

// WithSubmissionID sets the SubmissionID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubmissionID field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithSubmissionID(value string) *SparkApplicationStatusApplyConfiguration {
	b.SubmissionID = &value
	return b
}

// WithLastSubmissionAttemptTime sets the LastSubmissionAttemptTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSubmissionAttemptTime field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithLastSubmissionAttemptTime(value v1.Time) *SparkApplicationStatusApplyConfiguration {
	b.LastSubmissionAttemptTime = &value
	return b
}

// WithTerminationTime sets the TerminationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminationTime field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithTerminationTime(value v1.Time) *SparkApplicationStatusApplyConfiguration {
	b.TerminationTime = &value
	return b
}

// WithDriverInfo sets the DriverInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DriverInfo field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithDriverInfo(value *DriverInfoApplyConfiguration) *SparkApplicationStatusApplyConfiguration {
	b.DriverInfo = value
	return b
}

// WithAppState sets the AppState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppState field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithAppState(value *ApplicationStateApplyConfiguration) *SparkApplicationStatusApplyConfiguration {
	b.AppState = value
	return b
}

// WithExecutorState puts the entries into the ExecutorState field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExecutorState field,
// overwriting an existing map entries in ExecutorState field with the same key.
func (b *SparkApplicationStatusApplyConfiguration) WithExecutorState(entries map[string]apiv1beta2.ExecutorState) *SparkApplicationStatusApplyConfiguration {
	if b.ExecutorState == nil && len(entries) > 0 {
		b.ExecutorState = make(map[string]apiv1beta2.ExecutorState, len(entries))
	}
	for k, v := range entries {
		b.ExecutorState[k] = v
	}
	return b
}

// WithExecutionAttempts sets the ExecutionAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExecutionAttempts field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithExecutionAttempts(value int32) *SparkApplicationStatusApplyConfiguration {
	b.ExecutionAttempts = &value
	return b
}

// WithSubmissionAttempts sets the SubmissionAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubmissionAttempts field is set to the value of the last call.
func (b *SparkApplicationStatusApplyConfiguration) WithSubmissionAttempts(value int32) *SparkApplicationStatusApplyConfiguration {
	b.SubmissionAttempts = &value
	return b
}
