name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # TODO: Maintainer of repository to follow:
      # https://github.com/docker/login-action#google-container-registry-gcr to add credentials so
      # we can push from github actions
      # - name: log in to container registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: gcr.io
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release Spark-Operator Docker Image
        run: |
          DOCKER_TAG=$(cat charts/spark-operator-chart/Chart.yaml | grep "appVersion: .*" | cut -c13-)
          docker build -t gcr.io/spark-operator/spark-operator:${DOCKER_TAG} .
          echo "Ideally, we'd release the docker container at this point, but the maintainer of this repo needs to approve..."
          if ! docker pull docker pull gcr.io/spark-operator/spark-operator:${DOCKER_TAG}; then
            echo "docker push gcr.io/spark-operator/spark-operator:${DOCKER_TAG}"
            git tag $DOCKER_TAG
            git push origin $DOCKER_TAG
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "spark-operator-chart-{{ .Version }}"

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
